import { StyleSheet } from 'react-native';
import { typography, spacing, radius } from '@/constants/theme';

export const styles = StyleSheet.create({
  header: {
    paddingHorizontal: spacing[4],
    paddingTop: spacing[8],
    paddingBottom: spacing[3],
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing[4],
  },
  title: {
    fontSize: typography.size['2xl'],
    fontWeight: typography.weight.bold,
    fontFamily: typography.family.display,
    textTransform: 'uppercase',
    letterSpacing: 1,
    flex: 1,
  },

  card: {
    marginBottom: spacing[5],
    padding: spacing[5],
    borderRadius: 32,
    borderWidth: 1,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 8,
  },
  settingsBtn: {
    position: 'absolute',
    top: spacing[4],
    right: spacing[4],
    zIndex: 20,
    width: 48,
    height: 48,
    borderRadius: radius.full,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[4],
    marginBottom: spacing[5],
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  avatarInitial: {
    fontSize: typography.size.xl,
    fontWeight: typography.weight.bold,
    fontFamily: typography.family.display,
  },
  dotWrap: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 16,
    height: 16,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: radius.full,
    backgroundColor: '#22C55E',
  },
  userInfo: {
    flex: 1,
    gap: 4,
  },
  displayName: {
    fontSize: typography.size['3xl'],
    fontWeight: typography.weight.bold,
    fontFamily: typography.family.display,
    letterSpacing: typography.letterSpacing.relaxed,
  },
  statusText: {
    fontSize: typography.size.sm,
    fontFamily: typography.family.body,
  },
  statsRow: {
    flexDirection: 'row',
    gap: spacing[3],
  },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderWidth: 1,
    borderRadius: radius['2xl'],
    padding: spacing[3],
    gap: spacing[2],
  },
  statCardLabel: {
    fontSize: typography.size.xs,
    fontFamily: typography.family.display,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  statCardValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing[1],
  },
  statCardBig: {
    fontSize: typography.size['3xl'],
    fontFamily: typography.family.display,
    fontWeight: typography.weight.bold,
  },
  statCardSub: {
    fontSize: typography.size.sm,
    fontFamily: typography.family.body,
    paddingBottom: spacing[1],
  },
  statCardAccent: {
    fontSize: typography.size.sm,
    fontFamily: typography.family.bodySemibold,
    fontWeight: typography.weight.bold,
  },
  miniGraph: {
    marginTop: -spacing[5],
    height: spacing[10],
  },

  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing[2],
    paddingBottom: spacing[2],
  },
  sectionTitle: {
    fontSize: typography.size.base,
    fontFamily: typography.family.display,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  list: {
    padding: spacing[4],
    gap: spacing[3],
    paddingBottom: 140,
  },
  fabRow: {
    position: 'absolute',
    bottom: spacing[4],
    left: spacing[5],
    right: spacing[5],
    flexDirection: 'row',
    gap: spacing[3],
  },
});
